content_lock.settings:
  type: config_object
  mapping:
    verbose:
      type: integer
      label: 'Display content lock messages'
    types:
      type: sequence
      label: 'Types'
      sequence:
        type: sequence
        label: 'Entity type'
        sequence:
          type: string
          label: 'Bundle type'
    types_translation_lock:
      type: sequence
      label: 'Entity types with translation lock on'
